# Generated by Django 4.2.9 on 2025-08-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='فروشگاه آنلاین', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=50)),
                ('support_address', models.CharField(blank=True, max_length=500)),
                ('primary_color', models.CharField(default='#2563eb', max_length=7)),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
