# Generated by Django 4.2.9 on 2025-08-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='primary_color',
        ),
    ]
