# Generated by Django 4.2.9 on 2025-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sitesettings_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_enabled',
            field=models.BooleanField(default=False, verbose_name='حالت نگه\u200cداری'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(blank=True, default='سایت موقتاً در حال بروزرسانی است. لطفاً دقایقی دیگر مراجعه کنید.', verbose_name='متن پیام حالت نگه\u200cداری'),
        ),
    ]
