# Generated by Django 4.2.9 on 2025-08-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن')),
                ('subject', models.CharField(choices=[('support', 'پشتیبانی فنی'), ('sales', 'فروش و خرید'), ('complaint', 'شکایت'), ('suggestion', 'پیشنهاد'), ('other', 'سایر')], max_length=20, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('privacy_accepted', models.BooleanField(verbose_name='موافقت با قوانین و مقررات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
        ),
    ]
