# Generated by Django 4.2.9 on 2025-08-10 09:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید به صورت شماره موبایل ایرانی معتبر وارد شود. مثلاً 09123456789 یا +989123456789.', regex='^(?:\\+98|0)?9\\d{9}$')], verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پروفایل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
