# Generated by Django 4.2.9 on 2025-08-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر'), ('customer', 'مشتری')], default='customer', max_length=20, verbose_name='نقش کاربر'),
        ),
    ]
