# Generated by Django 4.2.9 on 2025-08-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_alter_product_options_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
