# Generated by Django 4.2.9 on 2025-08-05 05:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='ویژگی\u200cهای کلیدی'),
        ),
    ]
