# Generated by Django 4.2.9 on 2025-08-05 05:47

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_key_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='key_features',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Key Features'),
        ),
    ]
