# Generated by Django 4.2.9 on 2025-08-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_discount_percent_alter_product_key_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='key_features',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Category Icon'),
        ),
    ]
