# Generated by Django 4.2.9 on 2025-08-08 12:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_key_features_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Key Features'),
        ),
    ]
